# This file was generated by liblab | https://liblab.com/

from open_hue import OpenHue, Environment

sdk = OpenHue(
    api_key="YOUR_API_KEY",
    api_key_header="YOUR_API_KEY_HEADER",
    base_url=Environment.DEFAULT.value,
)

result = sdk.resource.get_resources()

print(result)
